# Generated by Django 4.0.6 on 2022-07-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_cuisine_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secondary_description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('is_avaliable', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.cuisine')),
            ],
        ),
    ]
